
--Q1Q1. What is the total revenue generated by male vs. female customers?
SELECT
    "Gender",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Gender";

Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    "Customer ID",
    "Gender",
    "Age",
    "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >
      (SELECT AVG("Purchase Amount (USD)") FROM customer);

Q3. Which are the top 5 products with the highest average review rating?
SELECT
    "Item Purchased",
    AVG("Review Rating") AS avg_review_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_review_rating DESC
LIMIT 5;

Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

Q5. Do subscribed customers spend more? Compare average spend and total revenue.
SELECT
    "Subscription Status",
    AVG("Purchase Amount (USD)") AS avg_spend,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";

Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    "Item Purchased",
    COUNT(*) FILTER (WHERE "Discount Applied" = 'Yes') * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;

Q7. Segment customers into New, Returning, and Loyal based on previous purchases.

Logic

New → 0

Returning → 1–5

Loyal → >5

SELECT
    CASE
        WHEN "Previous Purchases" = 0 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

Q8. What are the top 3 most purchased products within each category?
SELECT
    "Category",
    "Item Purchased",
    purchase_count
FROM (
    SELECT
        "Category",
        "Item Purchased",
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY "Category", "Item Purchased"
) t
WHERE rn <= 3;

Q9. Are repeat buyers (>5 previous purchases) also likely to subscribe?
SELECT
    "Subscription Status",
    COUNT(*) AS customer_count
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

Q10. What is the revenue contribution of each age group?
SELECT
    "Age_Group",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age_Group"
ORDER BY total_revenue DESC;

🔥 EXTRA INSIGHTFUL QUESTIONS (Self-Initiated)
Q11. Which Age Group + Subscription Status segment contributes the most revenue?
SELECT
    "Age_Group",
    "Subscription Status",
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age_Group", "Subscription Status"
ORDER BY total_revenue DESC;

Q12. Do loyal customers receive more discounts than others?
SELECT
    CASE
        WHEN "Previous Purchases" > 5 THEN 'Loyal'
        ELSE 'Other'
    END AS customer_segment,
    COUNT(*) FILTER (WHERE "Discount Applied" = 'Yes') * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY customer_segment;

Q13. Which product categories have high ratings but low sales volume?
SELECT
    "Category",
    AVG("Review Rating") AS avg_rating,
    COUNT(*) AS total_sales
FROM customer
GROUP BY "Category"
ORDER BY avg_rating DESC, total_sales ASC;

Q14. Is there a correlation between purchase frequency and review rating?
SELECT
    CORR("purchase frequency days", "Review Rating") AS correlation_value
FROM customer;

Q15. Which payment method has the highest average purchase amount?
SELECT
    "Payment Method",
    AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
GROUP BY "Payment Method"
ORDER BY avg_purchase_amount DESC;

Q16. Do customers buying seasonal items spend more?
SELECT
    "Season",
    AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
GROUP BY "Season"
ORDER BY avg_purchase_amount DESC;

Q17. Which location generates the highest revenue per customer?
SELECT
    "Location",
    SUM("Purchase Amount (USD)") AS total_revenue,
    COUNT(DISTINCT "Customer ID") AS unique_customers,
    SUM("Purchase Amount (USD)") / COUNT(DISTINCT "Customer ID") AS revenue_per_customer
FROM customer
GROUP BY "Location"
ORDER BY revenue_per_customer DESC;

Q18. Does Express shipping increase purchase amount compared to Standard for the same product?
SELECT
    "Item Purchased",
    "Shipping Type",
    AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Item Purchased", "Shipping Type"
ORDER BY "Item Purchased", avg_purchase_amount DESC;

Q19. Which products show the highest promotional intensity (discount usage)?
SELECT
    "Item Purchased",
    COUNT(*) FILTER (WHERE "Discount Applied" = 'Yes') * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC;

Q20. Do repeat buyers give higher review ratings than one-time buyers?
SELECT
    CASE
        WHEN "Previous Purchases" > 1 THEN 'Repeat Buyer'
        ELSE 'One-Time Buyer'
    END AS customer_type,
    AVG("Review Rating") AS avg_review_rating
FROM customer
GROUP BY customer_type;

